// ----------------------------------------------------------------------

export const paths = {
  // Dashboard
  dashboard: {
    root: '/dashboard',
    analytics: '/dashboard/analytics',
    users: '/dashboard/users',
    user: `/dashboard/user`,
    reports: '/dashboard/reports',
    report: `/dashboard/report`,
    settings: '/dashboard/settings',
    support: '/dashboard/support',
    webtoons: '/dashboard/webtoons',
    content: '/dashboard/content',
    notifications: '/dashboard/notifications',
    security: '/dashboard/security',
    logs: '/dashboard/logs',
    backup: '/dashboard/backup',
  },
  // Organization (Байгууллага)
  organization: {
    root: '/organization',
    list: '/organization/list',
    add: '/organization/add',
    edit: `/organization/edit`,
    view: `/organization/view`,
    subdomain: '/organization/subdomain',
  },
  // Payment & Invoice (Төлбөр & Нэхэмжлэл)
  payment: {
    root: '/payment',
    management: '/payment/management',
    history: '/payment/history',
    invoice: {
      root: '/payment/invoice',
      list: '/payment/invoice/list',
      create: '/payment/invoice/create',
      send: '/payment/invoice/send',
      report: '/payment/invoice/report',
      view: '/payment/invoice/view',
      edit: '/payment/invoice/edit',
    },
  },
  // Travel
  travel: {
    root: '/travel',
    tours: '/travel/tours',
    tour: `/travel/tour`,
    checkout: '/travel/checkout',
    orderCompleted: '/travel/order-completed',
    posts: '/travel/posts',
    post: `/travel/post`,
    about: '/travel/about',
    contact: '/travel/contact',
  },
  // Career
  career: {
    root: '/career',
    jobs: '/career/jobs',
    job: `/career/job`,
    posts: '/career/posts',
    post: `/career/post`,
    about: '/career/about',
    contact: '/career/contact',
  },
  // E-learning
  eLearning: {
    root: '/e-learning',
    courses: '/e-learning/courses',
    course: `/e-learning/course`,
    posts: '/e-learning/posts',
    post: `/e-learning/post`,
    about: '/e-learning/about',
    contact: '/e-learning/contact',
  },
  // E-commerce
  eCommerce: {
    root: '/e-commerce',
    products: '/e-commerce/products',
    product: `/e-commerce/product`,
    cart: '/e-commerce/cart',
    checkout: `/e-commerce/checkout`,
    orderCompleted: '/e-commerce/order-completed',
    wishlist: `/e-commerce/wishlist`,
    compare: `/e-commerce/compare`,
    account: {
      root: `/e-commerce/account`,
      personal: `/e-commerce/account/personal`,
      wishlist: `/e-commerce/account/wishlist`,
      vouchers: `/e-commerce/account/vouchers`,
      orders: `/e-commerce/account/orders`,
      payment: `/e-commerce/account/payment`,
    },
  },
  // Auth
  loginCover: '/auth/login-cover',
  loginBackground: '/auth/login-background',
  loginIllustration: '/auth/login-illustration',
  registerCover: '/auth/register-cover',
  registerBackground: '/auth/register-background',
  registerIllustration: '/auth/register-illustration',
  forgotPassword: '/auth/forgot-password',
  verify: '/auth/verify',
  // Common
  maintenance: '/maintenance',
  comingsoon: '/coming-soon',
  pricing01: '/pricing-01',
  pricing02: '/pricing-02',
  support: '/support',
  page404: '/error/404',
  page500: '/error/500',
  // Components
  components: {
    root: '/components',
    animate: '/components/animate',
    carousel: '/components/carousel',
    countUp: '/components/count-up',
    form: '/components/form-validation',
    icons: '/components/icons',
    image: '/components/image',
    label: '/components/label',
    lightbox: '/components/lightbox',
    markdown: '/components/markdown',
    megaMenu: '/components/mega-menu',
    navigation: '/components/navigation-bar',
    scroll: '/components/scroll',
    player: '/components/player',
    textMaxLine: '/components/text-max-line',
  },
  // Others
  pages: '/pages',
  docs: 'https://zone-docs.vercel.app',
  license: 'https://material-ui.com/store/license/#i-standard-license',
  minimalStore: 'https://material-ui.com/store/items/minimal-dashboard',
  zoneStore: 'https://mui.com/store/items/zone-landing-page/',
  figmaPreview:
    'https://www.figma.com/file/X6OyiGHF8dnTk3aT38P0oN/%5BPreview%5D-Zone_Web.30.03.23?node-id=0-1',
};
