import { paths } from 'src/routes/paths';

// ----------------------------------------------------------------------

export const pageLinks = [
  {
    order: '1',
    subheader: 'Үндсэн',
    cover: '/assets/images/menu/menu_marketing.jpg',
    items: [
      { title: 'Нүүр', path: paths.dashboard.root },
      { title: 'Аналитик', path: paths.dashboard.analytics },
      { title: 'Тайлан', path: paths.dashboard.reports },
    ],
  },
  {
    order: '2',
    subheader: 'Удирдлага',
    cover: '/assets/images/menu/menu_marketing.jpg',
    items: [
      { title: 'Хэрэглэгчид', path: paths.dashboard.users },
      { title: 'Вэбтоон', path: paths.dashboard.webtoons },
      { title: 'Контент', path: paths.dashboard.content },
    ],
  },
  {
    order: '3',
    subheader: 'Систем',
    cover: '/assets/images/menu/menu_marketing.jpg',
    items: [
      { title: 'Мэдэгдэл', path: paths.dashboard.notifications },
      { title: 'Аюулгүй байдал', path: paths.dashboard.security },
      { title: 'Лог', path: paths.dashboard.logs },
      { title: 'Нөөцлөл', path: paths.dashboard.backup },
    ],
  },
  {
    order: '4',
    subheader: 'Тусламж',
    cover: '/assets/images/menu/menu_marketing.jpg',
    items: [
      { title: 'Тохиргоо', path: paths.dashboard.settings },
      { title: 'Дэмжлэг', path: paths.dashboard.support },
    ],
  },
  {
    order: '6',
    subheader: 'Аялал',
    cover: '/assets/images/menu/menu_travel.jpg',
    items: [
      { title: 'Нүүр хуудас', path: paths.travel.root },
      { title: 'Аяллууд', path: paths.travel.tours },
      { title: 'Аялал', path: paths.travel.tour },
      { title: 'Төлбөр', path: paths.travel.checkout },
      { title: 'Захиалга дууссан', path: paths.travel.orderCompleted },
      { title: 'Блогийн нийтлэлүүд', path: paths.travel.posts },
      { title: 'Блогийн нийтлэл', path: paths.travel.post },
      { title: 'Бидний тухай', path: paths.travel.about },
      { title: 'Холбоо барих', path: paths.travel.contact },
    ],
  },
  {
    order: '2',
    subheader: 'Карьер',
    cover: '/assets/images/menu/menu_career.jpg',
    items: [
      { title: 'Нүүр хуудас', path: paths.career.root },
      { title: 'Ажлын байрууд', path: paths.career.jobs },
      { title: 'Ажлын байр', path: paths.career.job },
      { title: 'Блогийн нийтлэлүүд', path: paths.career.posts },
      { title: 'Блогийн нийтлэл', path: paths.career.post },
      { title: 'Бидний тухай', path: paths.career.about },
      { title: 'Холбоо барих', path: paths.career.contact },
    ],
  },
  {
    order: '5',
    subheader: 'Цахим сургалт',
    cover: '/assets/images/menu/menu_elearning.jpg',
    items: [
      { title: 'Нүүр хуудас', path: paths.eLearning.root },
      { title: 'Хичээлүүд', path: paths.eLearning.courses },
      { title: 'Хичээл', path: paths.eLearning.course },
      { title: 'Блогийн нийтлэлүүд', path: paths.eLearning.posts },
      { title: 'Блогийн нийтлэл', path: paths.eLearning.post },
      { title: 'Бидний тухай', path: paths.eLearning.about },
      { title: 'Холбоо барих', path: paths.eLearning.contact },
    ],
  },
  {
    isNew: true,
    order: '3',
    subheader: 'Цахим худалдаа',
    cover: '/assets/images/menu/menu_ecommerce.jpg',
    items: [
      { title: 'Нүүр хуудас', path: paths.eCommerce.root },
      { title: 'Бүтээгдэхүүн', path: paths.eCommerce.products },
      { title: 'Бүтээгдэхүүн', path: paths.eCommerce.product },
      { title: 'Сагс', path: paths.eCommerce.cart },
      { title: 'Төлбөр', path: paths.eCommerce.checkout },
      { title: 'Захиалга дууссан', path: paths.eCommerce.orderCompleted },
      { title: 'Хүслийн жагсаалт', path: paths.eCommerce.wishlist },
      { title: 'Харьцуулах', path: paths.eCommerce.compare },
      { title: 'Хувийн мэдээлэл', path: paths.eCommerce.account.personal },
      { title: 'Хүслийн жагсаалт', path: paths.eCommerce.account.wishlist },
      { title: 'Купонууд', path: paths.eCommerce.account.vouchers },
      { title: 'Захиалгууд', path: paths.eCommerce.account.orders },
      { title: 'Төлбөр', path: paths.eCommerce.account.payment },
    ],
  },
  {
    order: '4',
    subheader: 'Нийтлэг',
    items: [
      { title: 'Нэвтрэх хуудас 1', path: paths.loginCover },
      { title: 'Нэвтрэх хуудас 2', path: paths.loginIllustration },
      { title: 'Нэвтрэх хуудас 3', path: paths.loginBackground },
      { title: 'Бүртгүүлэх хуудас 1', path: paths.registerCover },
      { title: 'Бүртгүүлэх хуудас 2', path: paths.registerIllustration },
      { title: 'Бүртгүүлэх хуудас 3', path: paths.registerBackground },
      { title: 'Нууц үг мартсан', path: paths.forgotPassword },
      { title: 'Код баталгаажуулах', path: paths.verify },
      { title: '404 Алдаа', path: paths.page404 },
      { title: '500 Алдаа', path: paths.page500 },
      { title: 'Засвар үйлчилгээ', path: paths.maintenance },
      { title: 'Удахгүй', path: paths.comingsoon },
      { title: 'Үнийн санал 1', path: paths.pricing01 },
      { title: 'Үнийн санал 2', path: paths.pricing02 },
      { title: 'Төлбөр', path: paths.payment },
      { title: 'Дэмжлэг', path: paths.support },
    ],
  },
];

export const navConfig = [
  {
    title: 'Хяналтын самбар',
    path: paths.dashboard.root,
    icon: 'solar:home-2-bold',
    badge: 'Шинэ',
    navKey: 'dashboard',
  },
  {
    title: 'Аналитик',
    path: paths.dashboard.analytics,
    icon: 'solar:chart-2-bold',
    navKey: 'analytics',
  },
  {
    title: 'Тайлан',
    path: paths.dashboard.reports,
    icon: 'solar:file-text-bold',
    navKey: 'reports',
  },
  {
    title: 'Хэрэглэгчид',
    path: paths.dashboard.users,
    icon: 'solar:users-group-rounded-bold',
    navKey: 'users',
  },
  {
    title: 'Вэбтоон',
    path: paths.dashboard.webtoons,
    icon: 'solar:book-2-bold',
    navKey: 'webtoons',
  },
  {
    title: 'Контент',
    path: paths.dashboard.content,
    icon: 'solar:gallery-bold',
    navKey: 'content',
  },
  {
    title: 'Байгууллага',
    path: paths.organization.root,
    icon: 'solar:buildings-2-bold',
    navKey: 'organization',
  },
  {
    title: 'Төлбөрийн удирдлага',
    path: paths.payment.root,
    icon: 'solar:card-bold',
    navKey: 'paymentManagement',
    children: [
      { title: 'Үзүүлэлт', path: paths.payment.root, navKey: 'payment' },
      { title: 'Төлбөрийн түүх', path: paths.payment.history, navKey: 'paymentHistory' },
      { title: 'Нэхэмжлэлийн жагсаалт', path: paths.payment.invoice.list, navKey: 'invoiceList' },
      { title: 'Шинэ нэхэмжлэл', path: paths.payment.invoice.create, navKey: 'invoiceCreate' },
      { title: 'Нэхэмжлэл илгээх', path: paths.payment.invoice.send, navKey: 'invoiceSend' },
      { title: 'Нэхэмжлэлийн тайлан', path: paths.payment.invoice.report, navKey: 'invoiceReport' },
    ],
  },
  {
    title: 'Мэдэгдэл',
    path: paths.dashboard.notifications,
    icon: 'solar:bell-bold',
    navKey: 'notifications',
  },
  {
    title: 'Аюулгүй байдал',
    path: paths.dashboard.security,
    icon: 'solar:shield-bold',
    navKey: 'security',
  },
  {
    title: 'Лог',
    path: paths.dashboard.logs,
    icon: 'solar:document-text-bold',
    navKey: 'logs',
  },
  {
    title: 'Нөөцлөл',
    path: paths.dashboard.backup,
    icon: 'solar:database-bold',
    navKey: 'backup',
  },
  {
    title: 'Тохиргоо',
    path: paths.dashboard.settings,
    icon: 'solar:settings-bold',
    navKey: 'settings',
  },
  {
    title: 'Дэмжлэг',
    path: paths.dashboard.support,
    icon: 'solar:headphones-bold',
    navKey: 'support',
  },
  {
    title: 'Компонент',
    path: paths.components.root,
    icon: 'solar:widget-2-bold',
    navKey: 'components',
  },
  {
    title: 'Хуудас',
    path: paths.pages,
    icon: 'solar:file-bold',
    navKey: 'pages',
    children: [pageLinks[4], pageLinks[5]],
  },
  {
    title: 'Баримт',
    path: paths.docs,
    icon: 'solar:book-bold',
    navKey: 'docs',
  },
];
